# Generated by Django 2.1.5 on 2020-09-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200912_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='project_name',
            field=models.CharField(default='Project', max_length=30),
        ),
    ]
